### ISSUE TITLE
Not happy with File io functions

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/bos#34]

**Comment by samoht** [comment]
why?

**Comment by dbuenzli** [comment]
I think [`OS.File.fold_lines`](http://erratique.ch/software/bos/doc/Bos.OS.File.html#VALfold_lines) doesn't work quite well in practice if you need to handle errors. I'd prefer a bracketed pull interface `with_input_lines` in the style of [`OS.File.with_input`](http://erratique.ch/software/bos/doc/Bos.OS.File.html#VALwith_input) that allows you to write a function that acts on a stream of strings (one per line) that you get by calling a function. It could maybe even return a stream of substrings representing lines.

**Comment by dbuenzli** [comment]
> well in practice if you need to handle parse errors.

Rather in fact if you want to consume the stream in parallel with another one (e.g. to compare side-by-side to a list, or another stream).

**Comment by dbuenzli** [comment]
Bah fundamentally what I want here is a streaming framework let's pray @pqwy.
