### ISSUE TITLE
Path should be forked away

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/bos#37]
It can be used in a variety of other contexts and offers a much more decent `Filename` module. But people may not like the `Unix` dependency or the rest provided by `bos`.

The only problem is that I do not want to expose it as yet another namespace and squatting the toplevel `Path` name is bad. `Fpath`, `Filepath`, `Fspath` could be options.

We'd also loose the nice toplevel `path` name you can use in signatures whenever you open `Bos` which will make signatures a little more busy. But I can get over that.

**Comment by rgrinberg** [comment]
Have you considered creating multiple opam packages out of a single git repo? It seems to solve the dependency factoring problem while still making it easy to avoid constraints hell. A disciplined maintainer can will of course avoid this problem regardless but it also makes it easier for users to keep track of libraries. Less git repos, bug trackers, etc.

**Comment by dbuenzli** [comment]
> makes it easier for users to keep track of libraries.

Well, want to file a bug on the fpath package ? Go to the github repo for fpath. I don't see what is being hard to track here.
