### ISSUE TITLE
Fix the OS.Cmd combinators on Windows.

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/bos#51]
See the hints given by @fdopen [here](https://github.com/dbuenzli/topkg/issues/28#issuecomment-221437586).

**Comment by dbuenzli** [comment]
Most of the things seem to be working now (in particular the `topkg` tool). But two tests are still failing. 

1. It seems that `OS.Cmd.to_file ~append:true` doesn't work. Here's [how I open](https://github.com/dbuenzli/bos/blob/ecf6e8399dc9e255310db1a4c64cab45592c1161/src/bos_os_cmd.ml#L134-L139) the file, the code works on osx and linux. Do you know if there's any problem with `Unix.O_APPEND` on windows @fdopen ? 

2. Pipelining (`OS.Cmd.out_run_in`) seems to be broken. I need to investigate a little bit more into that but does maybe the following ring a bell:
  ```ocaml
  # OS.Cmd.(run_out Cmd.(v "ls") |> out_run_in) >>= fun pipe -> 
    OS.Cmd.(pipe |> run_io Cmd.(v "cat") |> to_lines);;
  utop.exe: [EXEC:244] ["ls"]
  utop.exe: [EXEC:316] ["cat"]
  ls: write error
  cat: failed to reopen ‘stdin’ with mode ‘rb’: Bad file descriptor
  - : (bytes list, [> Rresult.R.msg ]) result =
  Result.Error (`Msg "run [\"ls\"]: exited with 2")
  ```
  I suspect that it doesn't like that I [close the pipe in the parent](https://github.com/dbuenzli/bos/blob/ecf6e8399dc9e255310db1a4c64cab45592c1161/src/bos_os_cmd.ml#L330-L331) after the call to `create_process` to which I give the fd of the pipe for its stdin.

**Comment by fdopen** [comment]
It's unimplemented: http://caml.inria.fr/mantis/view.php?id=4431

**Comment by dbuenzli** [comment]
Thanks @fdopen for the reference (and general help) I now mention in the documentation that appending to files doesn't work on windows. 

The pipeline bug was a funny one, it was working on POSIX due the the way `Unix.create_process` is implemented (see the commit for details).

The `OS.Cmd` combinators seem now to work reasonably well on Windows® (and so does the `topkg` tool) so I'm closing this and making a release.
