### ISSUE TITLE
"type" / OS.Cmd.exists

### ISSUE THREAD

**Issue by fdopen** [dbuenzli/bos#52]
https://github.com/dbuenzli/bos/blob/8e65a1674b9fe554247d1264649444fd340f75b6/src/bos_os_cmd.ml#L85
`type` is only a shell-builtin on linux, `apt-file search 'bin/type'` doesn't list something else. But `type`is called with create_process (fork/exec), not Sys.command.
( And using `Sys.command` instead is also prone to failure. It will report shell-builtins as available, that you can't call with create_process.)

**Comment by dbuenzli** [comment]
Arf, that's annoying, `type` is [supposed](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/type.html) to be in POSIX. But indeed I blindly c&p `cmdliner`'s code which uses `Sys.command`. Maybe I should try with [`command -v`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html). I can't explain myself why I completly forgot to test `bos` on linux before releasing.

**Comment by dbuenzli** [comment]
Well it seems that `command` is builtin only. So how is one supposed to check for a command's existence on linux ?

**Comment by dbuenzli** [comment]
In https://github.com/dbuenzli/topkg/issues/39 @paurkedal suggests using `which`. This is not a standard POSIX tool but it seems to be present on Linux ubuntu, osx and the manpage says it first appeared on freebsd so I guess the bsds must have it. 

I'm going to use this for now, but maybe I should just reimplement a lookup by looking up for the utility in the directories of `PATH`.

**Comment by paurkedal** [comment]
I think `which` is quite common yes, it's present also on CentOS 7 and Fedora 23, both which should be fairly minimal installs.  OTOH, I may be wrong, but I don't think `which` is doing much more than iterate though `String.cuts ~sep:":" (Sys.getenv "PATH")` and checking presence and executable bit, so it could be replaced.

**Comment by dsheets** [comment]
`which` is not available by default with Nix so the opam package will need a `conf-which` to be universal, I think (`conf-which` is usually a no-op).

**Comment by dbuenzli** [comment]
Thanks David for the information. I added the dependency on `conf-which` and opened https://github.com/dbuenzli/bos/issues/53 to get rid of it.
