### ISSUE TITLE
Bos.OS.Cmd.to_string hangs indefinitely if the command does not exist

### ISSUE THREAD

**Issue by hcarty** [dbuenzli/bos#58]
Testing in utop, the following hangs indefinitely (OCaml 4.02.3 64bit, OSX 10.11, Bos 0.1.3 from opam):

```ocaml
#require "bos.top";;
Bos.Cmd.v "fake" |> Bos.OS.Cmd.run_out |> Bos.OS.Cmd.to_string;;
```

**Comment by dbuenzli** [comment]
This is a `utop` bug it does all sorts of things I don't want to know about (see e.g. https://github.com/diml/utop/issues/152). Try with `ocaml` you'll see there's no problem: 

```ocaml
# Bos.Cmd.v "fake" |> Bos.OS.Cmd.run_out |> Bos.OS.Cmd.to_string;;
ocaml: [EXEC:45867] ['fake']
- : (string, _[> Rresult.R.msg ]) Bos.OS.result =
Result.Error (`Msg "run ['fake']: exited with 127")
```

**Comment by hcarty** [comment]
Ah, thank you!  Sorry for the noise.

**Comment by dbuenzli** [comment]
> Ah, thank you! Sorry for the noise.

No problem. May not be evident to figure out...
