### ISSUE TITLE
Normalization of Unix.select behavior for windows.

### ISSUE THREAD

**Issue by jordwalke** [dbuenzli/bos#74]
I was curious if `bos` would be a suitable place to normalize the behavior of `Unix.select` across various operating systems, (and for versions of OCaml (`< 4.08` likely) which will not receive a core standard library fix).

https://caml.inria.fr/mantis/view.php?id=7665

**Comment by dbuenzli** [comment]
> (and for versions of OCaml (< 4.08 likely)

We should make sure a fix gets in `4.07`. Currently `bos` has no C bindings and tends to be not so `Unix`y in the interfaces it exposes. I'm not formally against it but maybe @ygrek's [extunix](https://github.com/ygrek/extunix/tree/master/src) could be a more natural place for that.

**Comment by dbuenzli** [comment]
Let's not do that.
