### ISSUE TITLE
Bos.OS.Path.symlink ~force:true does not unlink reliably

### ISSUE THREAD

**Issue by avsm** [dbuenzli/bos#75]
```
# Bos.OS.Path.symlink ~force:true ~target:Fpath.(v "foo") Fpath.(v "bar") ;;
- : (unit, _[> Rresult.R.msg ]) result = Result.Ok ()
# Bos.OS.Path.symlink ~force:true ~target:Fpath.(v "foo") Fpath.(v "bar") ;;
- : (unit, _[> Rresult.R.msg ]) result =
Result.Error (`Msg "force symlink foo to bar: No such file or directory")
# Bos.OS.Path.symlink ~target:Fpath.(v "foo") Fpath.(v "bar") ;;
- : (unit, _[> Rresult.R.msg ]) result =
Result.Error (`Msg "symlink foo to bar: File exists")
```

Unlinking before the symlink call works reliably, but I think the `force:true` should save this call.

**Comment by dbuenzli** [comment]
Mmmh that's odd. Unless I miss something there seem to be some kind of POSIX behaviour divergence here. The second call should return `EEXIST` and as a far as I can tell this is handled by the [code](https://github.com/dbuenzli/bos/blob/97b0093541fcebb0179077d365f5bf04442aa072/src/bos_os_path.ml#L218-L225).

**Comment by dbuenzli** [comment]
The error is in `force_remove`, [here](https://github.com/dbuenzli/bos/blob/97b0093541fcebb0179077d365f5bf04442aa072/src/bos_os_path.ml#L200) this should be `lstat`.
