### ISSUE TITLE
no API online

### ISSUE THREAD

**Issue by UnixJunkie** [dbuenzli/bos#80]
https://erratique.ch/software/bos/doc

"the requested page does not exist"

**Comment by dbuenzli** [comment]
Thanks for the report ! 

This seems a glitch from my recent host and https migration, I'll try to fix it asap. Meanwhile the documentation is still there though use `https://erratique.ch/software/bos/doc/index.html`.

**Comment by dbuenzli** [comment]
I think this is now fixed. Do not hesistate to report further glitches.
