### ISSUE TITLE
The behavior of `OS.Cmd.out_lines ~trim:true` is confusing

### ISSUE THREAD

**Issue by Armael** [dbuenzli/bos#85]
Just reporting that I just got confused for a moment by the behavior of `out_lines ~trim:true`.
I would have expected `String.trim` to be called on each line individually; instead, `String.trim` is called on the whole input before line splitting.

**Comment by dbuenzli** [comment]
Indeed. This function should likely not exist at all, `out_string` should simply be composed with a splitter of your own.

**Comment by dbuenzli** [comment]
I stand by my comment, but the function exists now. So I just added a bit of documentation.
