### ISSUE TITLE
bos.0.2.1 build for 5.00.0+trunk

### ISSUE THREAD

**Issue by shakthimaan** [dbuenzli/bos#92]
`bos.0.2.1` builds fine for OCaml 5.00.0+trunk after replacing the `Pervasives` module with the `Stdlib`.

Would it be possible for you to review the patch changes, or do you already have a patch?

**Comment by dbuenzli** [comment]
Could you provide a link to the patch please.

**Comment by shakthimaan** [comment]
[bos-use-stdlib.patch.txt](https://github.com/dbuenzli/bos/files/8050097/bos-use-stdlib.patch.txt)

**Comment by dbuenzli** [comment]
I tested 0.2.1 on an `5.00` switch and it works fine. Feel free to reopen if you think there's a problem.
